# python s1040checkCoverage.py /Users/bogdan/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt /Users/bogdan/elisp/_ghdata/corp/ukcorpus2014/frqDict-internet-ua.txt >/Users/bogdan/elisp/_ghdata/corp/dict_uk_expand_lists/cov12.txt
# python s1040checkCoverage.py /Users/bogdan/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt /Users/bogdan/elisp/_ghdata/corp/ukcorpus/news.tokenized.shuffled_uk-frqdict.txt >/Users/bogdan/elisp/_ghdata/corp/dict_uk_expand_lists/cov17news.txt


## python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus2014/frqDict-internet-ua.txt' >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/cov12.txt'
## python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/news.tokenized.shuffled_uk-frqdict.txt' >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/cov17news.txt'



python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/corpus_all_tokenized_uk-frqdict.txt' 20 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/corpus_all_tokenized_uk-cov1720.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/fiction.tokenized.shuffled_uk-frqdict.txt' 20 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/fiction.tokenized.shuffled_uk-cov1720.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/laws.txt.tokenized_uk-frqdict.txt' 20 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/laws.txt.tokenized_uk-cov1720.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/news.tokenized.shuffled_uk-frqdict.txt' 20 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/news.tokenized.shuffled_uk-cov1720.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/wiki_dump.lemmatized_uk-frqdict.txt' 20 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/wiki_dump.lemmatized_uk-cov1720.txt'


python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/corpus_all_tokenized_uk-frqdict.txt' 30 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/corpus_all_tokenized_uk-cov1730.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/fiction.tokenized.shuffled_uk-frqdict.txt' 30 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/fiction.tokenized.shuffled_uk-cov1730.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/laws.txt.tokenized_uk-frqdict.txt' 30 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/laws.txt.tokenized_uk-cov1730.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/news.tokenized.shuffled_uk-frqdict.txt' 30 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/news.tokenized.shuffled_uk-cov1730.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/wiki_dump.lemmatized_uk-frqdict.txt' 30 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/wiki_dump.lemmatized_uk-cov1730.txt'


python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/corpus_all_tokenized_uk-frqdict.txt' 40 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/corpus_all_tokenized_uk-cov1740.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/fiction.tokenized.shuffled_uk-frqdict.txt' 40 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/fiction.tokenized.shuffled_uk-cov1740.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/laws.txt.tokenized_uk-frqdict.txt' 40 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/laws.txt.tokenized_uk-cov1740.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/news.tokenized.shuffled_uk-frqdict.txt' 40 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/news.tokenized.shuffled_uk-cov1740.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/wiki_dump.lemmatized_uk-frqdict.txt' 40 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/wiki_dump.lemmatized_uk-cov1740.txt'


python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/corpus_all_tokenized_uk-frqdict.txt' 50 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/corpus_all_tokenized_uk-cov1750.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/fiction.tokenized.shuffled_uk-frqdict.txt' 50 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/fiction.tokenized.shuffled_uk-cov1750.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/laws.txt.tokenized_uk-frqdict.txt' 50 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/laws.txt.tokenized_uk-cov1750.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/news.tokenized.shuffled_uk-frqdict.txt' 50 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/news.tokenized.shuffled_uk-cov1750.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/wiki_dump.lemmatized_uk-frqdict.txt' 50 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/wiki_dump.lemmatized_uk-cov1750.txt'


python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/corpus_all_tokenized_uk-frqdict.txt' 60 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/corpus_all_tokenized_uk-cov1760.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/fiction.tokenized.shuffled_uk-frqdict.txt' 60 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/fiction.tokenized.shuffled_uk-cov1760.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/laws.txt.tokenized_uk-frqdict.txt' 60 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/laws.txt.tokenized_uk-cov1760.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/news.tokenized.shuffled_uk-frqdict.txt' 60 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/news.tokenized.shuffled_uk-cov1760.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/wiki_dump.lemmatized_uk-frqdict.txt' 60 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/wiki_dump.lemmatized_uk-cov1760.txt'


python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/corpus_all_tokenized_uk-frqdict.txt' 70 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/corpus_all_tokenized_uk-cov1770.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/fiction.tokenized.shuffled_uk-frqdict.txt' 70 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/fiction.tokenized.shuffled_uk-cov1770.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/laws.txt.tokenized_uk-frqdict.txt' 70 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/laws.txt.tokenized_uk-cov1770.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/news.tokenized.shuffled_uk-frqdict.txt' 70 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/news.tokenized.shuffled_uk-cov1770.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/wiki_dump.lemmatized_uk-frqdict.txt' 70 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/wiki_dump.lemmatized_uk-cov1770.txt'


python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/corpus_all_tokenized_uk-frqdict.txt' 80 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/corpus_all_tokenized_uk-cov1780.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/fiction.tokenized.shuffled_uk-frqdict.txt' 80 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/fiction.tokenized.shuffled_uk-cov1780.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/laws.txt.tokenized_uk-frqdict.txt' 80 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/laws.txt.tokenized_uk-cov1780.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/news.tokenized.shuffled_uk-frqdict.txt' 80 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/news.tokenized.shuffled_uk-cov1780.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/wiki_dump.lemmatized_uk-frqdict.txt' 80 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/wiki_dump.lemmatized_uk-cov1780.txt'


python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/corpus_all_tokenized_uk-frqdict.txt' 90 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/corpus_all_tokenized_uk-cov1790.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/fiction.tokenized.shuffled_uk-frqdict.txt' 90 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/fiction.tokenized.shuffled_uk-cov1790.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/laws.txt.tokenized_uk-frqdict.txt' 90 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/laws.txt.tokenized_uk-cov1790.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/news.tokenized.shuffled_uk-frqdict.txt' 90 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/news.tokenized.shuffled_uk-cov1790.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/wiki_dump.lemmatized_uk-frqdict.txt' 90 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/wiki_dump.lemmatized_uk-cov1790.txt'


python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/corpus_all_tokenized_uk-frqdict.txt' 100 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/corpus_all_tokenized_uk-cov1800.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/fiction.tokenized.shuffled_uk-frqdict.txt' 100 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/fiction.tokenized.shuffled_uk-cov1800.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/laws.txt.tokenized_uk-frqdict.txt' 100 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/laws.txt.tokenized_uk-cov1800.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/news.tokenized.shuffled_uk-frqdict.txt' 100 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/news.tokenized.shuffled_uk-cov1800.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/wiki_dump.lemmatized_uk-frqdict.txt' 100 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/wiki_dump.lemmatized_uk-cov1800.txt'


python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/corpus_all_tokenized_uk-frqdict.txt' 110 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/corpus_all_tokenized_uk-cov1810.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/fiction.tokenized.shuffled_uk-frqdict.txt' 110 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/fiction.tokenized.shuffled_uk-cov1810.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/laws.txt.tokenized_uk-frqdict.txt' 110 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/laws.txt.tokenized_uk-cov1810.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/news.tokenized.shuffled_uk-frqdict.txt' 110 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/news.tokenized.shuffled_uk-cov1810.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/wiki_dump.lemmatized_uk-frqdict.txt' 110 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/wiki_dump.lemmatized_uk-cov1810.txt'


python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/corpus_all_tokenized_uk-frqdict.txt' 120 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/corpus_all_tokenized_uk-cov1820.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/fiction.tokenized.shuffled_uk-frqdict.txt' 120 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/fiction.tokenized.shuffled_uk-cov1820.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/laws.txt.tokenized_uk-frqdict.txt' 120 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/laws.txt.tokenized_uk-cov1820.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/news.tokenized.shuffled_uk-frqdict.txt' 120 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/news.tokenized.shuffled_uk-cov1820.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/wiki_dump.lemmatized_uk-frqdict.txt' 120 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/wiki_dump.lemmatized_uk-cov1820.txt'

