# python s1040checkCoverage.py /Users/bogdan/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt /Users/bogdan/elisp/_ghdata/corp/ukcorpus2014/frqDict-internet-ua.txt >/Users/bogdan/elisp/_ghdata/corp/dict_uk_expand_lists/cov12.txt
# python s1040checkCoverage.py /Users/bogdan/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt /Users/bogdan/elisp/_ghdata/corp/ukcorpus/news.tokenized.shuffled_uk-frqdict.txt >/Users/bogdan/elisp/_ghdata/corp/dict_uk_expand_lists/cov17news.txt


## python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus2014/frqDict-internet-ua.txt' >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/cov12.txt'
## python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/news.tokenized.shuffled_uk-frqdict.txt' >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/cov17news.txt'


python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/corpus_all_tokenized_uk-frqdict.txt' 0 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/corpus_all_tokenized_uk-cov1700.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/fiction.tokenized.shuffled_uk-frqdict.txt' 0 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/fiction.tokenized.shuffled_uk-cov1700.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/laws.txt.tokenized_uk-frqdict.txt' 0 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/laws.txt.tokenized_uk-cov1700.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/news.tokenized.shuffled_uk-frqdict.txt' 0 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/news.tokenized.shuffled_uk-cov1700.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/wiki_dump.lemmatized_uk-frqdict.txt' 0 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/wiki_dump.lemmatized_uk-cov1700.txt'


python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/corpus_all_tokenized_uk-frqdict.txt' 1 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/corpus_all_tokenized_uk-cov1701.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/fiction.tokenized.shuffled_uk-frqdict.txt' 1 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/fiction.tokenized.shuffled_uk-cov1701.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/laws.txt.tokenized_uk-frqdict.txt' 1 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/laws.txt.tokenized_uk-cov1701.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/news.tokenized.shuffled_uk-frqdict.txt' 1 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/news.tokenized.shuffled_uk-cov1701.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/wiki_dump.lemmatized_uk-frqdict.txt' 1 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/wiki_dump.lemmatized_uk-cov1701.txt'


python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/corpus_all_tokenized_uk-frqdict.txt' 2 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/corpus_all_tokenized_uk-cov1702.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/fiction.tokenized.shuffled_uk-frqdict.txt' 2 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/fiction.tokenized.shuffled_uk-cov1702.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/laws.txt.tokenized_uk-frqdict.txt' 2 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/laws.txt.tokenized_uk-cov1702.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/news.tokenized.shuffled_uk-frqdict.txt' 2 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/news.tokenized.shuffled_uk-cov1702.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/wiki_dump.lemmatized_uk-frqdict.txt' 2 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/wiki_dump.lemmatized_uk-cov1702.txt'


python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/corpus_all_tokenized_uk-frqdict.txt' 3 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/corpus_all_tokenized_uk-cov1703.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/fiction.tokenized.shuffled_uk-frqdict.txt' 3 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/fiction.tokenized.shuffled_uk-cov1703.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/laws.txt.tokenized_uk-frqdict.txt' 3 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/laws.txt.tokenized_uk-cov1703.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/news.tokenized.shuffled_uk-frqdict.txt' 3 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/news.tokenized.shuffled_uk-cov1703.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/wiki_dump.lemmatized_uk-frqdict.txt' 3 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/wiki_dump.lemmatized_uk-cov1703.txt'


python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/corpus_all_tokenized_uk-frqdict.txt' 4 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/corpus_all_tokenized_uk-cov1704.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/fiction.tokenized.shuffled_uk-frqdict.txt' 4 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/fiction.tokenized.shuffled_uk-cov1704.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/laws.txt.tokenized_uk-frqdict.txt' 4 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/laws.txt.tokenized_uk-cov1704.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/news.tokenized.shuffled_uk-frqdict.txt' 4 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/news.tokenized.shuffled_uk-cov1704.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/wiki_dump.lemmatized_uk-frqdict.txt' 4 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/wiki_dump.lemmatized_uk-cov1704.txt'


python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/corpus_all_tokenized_uk-frqdict.txt' 5 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/corpus_all_tokenized_uk-cov1705.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/fiction.tokenized.shuffled_uk-frqdict.txt' 5 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/fiction.tokenized.shuffled_uk-cov1705.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/laws.txt.tokenized_uk-frqdict.txt' 5 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/laws.txt.tokenized_uk-cov1705.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/news.tokenized.shuffled_uk-frqdict.txt' 5 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/news.tokenized.shuffled_uk-cov1705.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/wiki_dump.lemmatized_uk-frqdict.txt' 5 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/wiki_dump.lemmatized_uk-cov1705.txt'


python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/corpus_all_tokenized_uk-frqdict.txt' 6 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/corpus_all_tokenized_uk-cov1706.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/fiction.tokenized.shuffled_uk-frqdict.txt' 6 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/fiction.tokenized.shuffled_uk-cov1706.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/laws.txt.tokenized_uk-frqdict.txt' 6 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/laws.txt.tokenized_uk-cov1706.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/news.tokenized.shuffled_uk-frqdict.txt' 6 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/news.tokenized.shuffled_uk-cov1706.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/wiki_dump.lemmatized_uk-frqdict.txt' 6 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/wiki_dump.lemmatized_uk-cov1706.txt'


python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/corpus_all_tokenized_uk-frqdict.txt' 7 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/corpus_all_tokenized_uk-cov1707.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/fiction.tokenized.shuffled_uk-frqdict.txt' 7 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/fiction.tokenized.shuffled_uk-cov1707.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/laws.txt.tokenized_uk-frqdict.txt' 7 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/laws.txt.tokenized_uk-cov1707.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/news.tokenized.shuffled_uk-frqdict.txt' 7 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/news.tokenized.shuffled_uk-cov1707.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/wiki_dump.lemmatized_uk-frqdict.txt' 7 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/wiki_dump.lemmatized_uk-cov1707.txt'


python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/corpus_all_tokenized_uk-frqdict.txt' 8 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/corpus_all_tokenized_uk-cov1708.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/fiction.tokenized.shuffled_uk-frqdict.txt' 8 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/fiction.tokenized.shuffled_uk-cov1708.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/laws.txt.tokenized_uk-frqdict.txt' 8 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/laws.txt.tokenized_uk-cov1708.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/news.tokenized.shuffled_uk-frqdict.txt' 8 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/news.tokenized.shuffled_uk-cov1708.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/wiki_dump.lemmatized_uk-frqdict.txt' 8 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/wiki_dump.lemmatized_uk-cov1708.txt'


python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/corpus_all_tokenized_uk-frqdict.txt' 9 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/corpus_all_tokenized_uk-cov1709.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/fiction.tokenized.shuffled_uk-frqdict.txt' 9 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/fiction.tokenized.shuffled_uk-cov1709.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/laws.txt.tokenized_uk-frqdict.txt' 9 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/laws.txt.tokenized_uk-cov1709.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/news.tokenized.shuffled_uk-frqdict.txt' 9 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/news.tokenized.shuffled_uk-cov1709.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/wiki_dump.lemmatized_uk-frqdict.txt' 9 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/wiki_dump.lemmatized_uk-cov1709.txt'


python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/corpus_all_tokenized_uk-frqdict.txt' 10 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/corpus_all_tokenized_uk-cov1710.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/fiction.tokenized.shuffled_uk-frqdict.txt' 10 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/fiction.tokenized.shuffled_uk-cov1710.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/laws.txt.tokenized_uk-frqdict.txt' 10 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/laws.txt.tokenized_uk-cov1710.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/news.tokenized.shuffled_uk-frqdict.txt' 10 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/news.tokenized.shuffled_uk-cov1710.txt'
python s1040checkCoverage.py '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/dict_corp_lt.txt' '/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/ukcorpus/wiki_dump.lemmatized_uk-frqdict.txt' 10 >'/Volumes/G-DRIVE mobile with Thunderbolt/elisp/_ghdata/corp/dict_uk_expand_lists/wiki_dump.lemmatized_uk-cov1710.txt'
